monocle install
bear-rsg/bear-eb pull request #34
Opened 2022-08-02 09:29 UTC by gyear

For INC1272027- `monocle-2.24.1-foss-2021b-R-4.2.0.eb`

* [ ] Assigned to reviewer

Default:
* [ ] EL8-icelake
* [ ] EL8-cascadelake
* [ ] EL8-haswell

2022-08-02 09:46 UTC, afraz-ahmed commented on easyconfigs/m/monocle/monocle-2.24.1-foss-2021b-R-4.2.0.eb
> +description = """"""
no description

2022-08-02 09:47 UTC, afraz-ahmed requested changes

2022-08-02 09:47 UTC, afraz-ahmed commented on easyconfigs/m/monocle/monocle-2.24.1-foss-2021b-R-4.2.0.eb
> +description = """"""
no description

2022-08-03 08:50 UTC, gyear commented
Waiting for reply from user to add module to BEAR-R-bio https://github.com/bear-rsg/bear-eb/blob/main/easyconfigs/b/BEAR-R-bio/BEAR-R-bio-2021b-foss-2021b-R-4.2.0.eb

2022-08-05 13:47 UTC, afraz-ahmed approved these changes

2022-08-05 14:31 UTC, merged