INC1502101 modkit install
bear-rsg/bear-eb pull request #398
Opened 2024-06-20 08:01 UTC by gyear

For INC150210 - `modkit-0.3.1rc1-GCCcore-12.2.0.eb`

* [ ] Assigned to reviewer

Default:
* [ ] EL8-icelake
* [ ] EL8-cascadelake

2024-06-21 10:21 UTC, orbsmiv requested changes

2024-06-21 10:21 UTC, orbsmiv commented on easyconfigs/m/modkit/modkit-0.3.1rc1-GCCcore-12.2.0-Rust-1.75.0.eb
> +versionsuffix = '-Rust-' + local_rustver
Looking at these easyconfs, I'm not sure it's necessary to have Rust in a version suffix, particularly as it's only a build dep:

- https://github.com/easybuilders/easybuild-easyconfigs/blob/cce1c8fdc5360d075d8c39cc34afb28b79fe40c4/easybuild/easyconfigs/m/mfqe/mfqe-0.5.0-GCC-12.3.0.eb
- https://github.com/easybuilders/easybuild-easyconfigs/blob/cce1c8fdc5360d075d8c39cc34afb28b79fe40c4/easybuild/easyconfigs/p/pydantic/pydantic-2.5.3-GCCcore-12.2.0.eb

2024-06-21 11:43 UTC, orbsmiv requested changes

2024-06-21 11:43 UTC, orbsmiv commented on easyconfigs/m/modkit/modkit-0.3.1rc1-GCCcore-12.2.0.eb
> +    ('Rust', local_rustver),
```suggestion
    ('Rust', '1.75.0'),
```

2024-06-21 11:43 UTC, orbsmiv commented on easyconfigs/m/modkit/modkit-0.3.1rc1-GCCcore-12.2.0.eb
> +versionsuffix = '-Rust-' + local_rustver
```suggestion
```

2024-06-21 11:43 UTC, orbsmiv commented on easyconfigs/m/modkit/modkit-0.3.1rc1-GCCcore-12.2.0.eb
> +crates = [
For consistency with other Cargo configs maybe move the `crates` list below the other deps?

2024-06-26 16:23 UTC, gyear commented
User conda installed

2024-06-26 16:23 UTC, closed without merging